# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 021535966c2e4612d6b8e1c026f712b3487cef4fffad20fb26aad70ec56cb7dcb52d59c5e3448b9b77bf3c1b7f96cbcec724b93b1bec7fc3e73d870b4c667da6

test:
  secret_key_base: 6174188caddadee371709a4281589535ee083e90f98cd783cae1c86d7c4d56bfe4144f0be8e54a379ff4d98642f9de672e3252531a43ca41f08a0fcf6ad87a6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
